### ISSUE TITLE
nil panic during static analysis

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/configkit#155]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x1495a6e]

goroutine 7 [running]:
github.com/dogmatiq/configkit/static.findConfigurerCalls(0xc0096ecc80, 0x0, 0xc0004eeda8, 0x1, 0x1, 0xc0004eeda8, 0x0, 0x1)
	/Users/james/go/pkg/mod/github.com/dogmatiq/configkit@v0.11.1-0.20210627063455-14abe13af60d/static/analysis.go:100 +0x16e
github.com/dogmatiq/configkit/static.findIndirectConfigurerCalls(0xc0096ecc80, 0xc00075d858, 0xc045d68b80, 0x2202ca0, 0x0, 0xc03d044030)
	/Users/james/go/pkg/mod/github.com/dogmatiq/configkit@v0.11.1-0.20210627063455-14abe13af60d/static/analysis.go:150 +0x165
github.com/dogmatiq/configkit/static.findConfigurerCalls(0xc0096ecc80, 0xc0319b0dc0, 0xc00075d810, 0x1, 0x0, 0x9, 0xc0319b0dc0, 0xc02621b5e0)
	/Users/james/go/pkg/mod/github.com/dogmatiq/configkit@v0.11.1-0.20210627063455-14abe13af60d/static/analysis.go:118 +0x350
github.com/dogmatiq/configkit/static.analyzeApplication(0xc0096ecc80, 0xc0258d0e10, 0xc026011ea0, 0xc026010af0, 0xc026204370, 0xc02620be00, 0xc02620aeb0, 0x1c66388, 0xc008e00500, 0x1c74638, ...)
	/Users/james/go/pkg/mod/github.com/dogmatiq/configkit@v0.11.1-0.20210627063455-14abe13af60d/static/analysis.go:31 +0x15f
github.com/dogmatiq/configkit/static.FromPackages(0xc03d9c80c0, 0x18, 0x18, 0xc01f8f2680, 0x2, 0x2)
	/Users/james/go/pkg/mod/github.com/dogmatiq/configkit@v0.11.1-0.20210627063455-14abe13af60d/static/static.go:52 +0x2e9
github.com/dogmatiq/docserve/analyzer.(*Analyzer).analyzePackages(0xc000190ea0, 0xc000590900, 0xc03d9c8000, 0x18, 0x18, 0xc06cd7a6f0, 0x28, 0xc03d9c8000)
	/Users/james/grit/github.com/dogmatiq/docserve/analyzer/analyze.go:231 +0x5f9
github.com/dogmatiq/docserve/analyzer.(*Analyzer).analyze(0xc000190ea0, 0x1c71ac8, 0xc000044900, 0xc000590900, 0x0, 0x0)
	/Users/james/grit/github.com/dogmatiq/docserve/analyzer/analyze.go:74 +0x5b3
github.com/dogmatiq/docserve/analyzer.(*Analyzer).Analyze(0xc000190ea0, 0x1c71ac8, 0xc000044900, 0xc000590900, 0xc000044910, 0x0)
	/Users/james/grit/github.com/dogmatiq/docserve/analyzer/analyze.go:31 +0x56
github.com/dogmatiq/docserve/analyzer.(*Orchestrator).handle(0xc000191140, 0x1c71ac8, 0xc000044900, 0xc000590900, 0x0, 0x1, 0x0)
	/Users/james/grit/github.com/dogmatiq/docserve/analyzer/orchestrator.go:51 +0xa7
github.com/dogmatiq/docserve/analyzer.(*Orchestrator).Run(0xc000191140, 0x1c71ac8, 0xc000044900, 0x1, 0x14)
	/Users/james/grit/github.com/dogmatiq/docserve/analyzer/orchestrator.go:31 +0x105
main.main.func1.1(0xc00008ca18, 0x8)
	/Users/james/grit/github.com/dogmatiq/docserve/cmd/docserve/main.go:47 +0x3c
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000120450, 0xc000074500)
	/Users/james/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/james/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
make: *** [run] Error 2
```

From router-gl@cwx, /cc @danilvpetrov

**Comment by jmalloc** [comment]
FYI, I am getting this now when analyzing `github.com/dogmatiq/dogma` itself
